/**
 * RDS dump이 적재된 staging Postgres에서 데이터를 읽어
 * Supabase 최종 스키마 형식의 migration-seed.sql을 생성한다.
 *
 * 사전 준비:
 *   docker run -d --name rds-staging -p 5500:5432 -e POSTGRES_PASSWORD=staging postgres:17
 *   → init.sql 적용 → pg_restore rds-data.dump
 *
 * 실행:
 *   tsx scripts/build-migration-seed.ts
 *
 * 출력:
 *   migration-seed.sql (gitignore — 운영 데이터 포함)
 *
 * 변환 규칙:
 *   public.user        → auth.users + auth.identities (Google OAuth)
 *   public.profile     → public.profile (userId/name/role 채움)
 *   public.post/book/author/profile_most_read_authors_author → 그대로
 */
import { Client } from "pg";
import { writeFileSync } from "fs";
import path from "path";

const STAGING_URL =
  process.env.STAGING_URL ?? "postgresql://postgres:staging@localhost:5500/postgres";
const OUTPUT_PATH = path.resolve(process.cwd(), "migration-seed.sql");

const ANON_INSTANCE_ID = "00000000-0000-0000-0000-000000000000";

function q(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value.toString();
  if (typeof value === "number") return value.toString();
  if (value instanceof Date) {
    return `'${value.toISOString().replace("T", " ").replace("Z", "+00")}'`;
  }
  const escaped = String(value).replace(/'/g, "''");
  return `'${escaped}'`;
}

function jsonb(value: object): string {
  const json = JSON.stringify(value).replace(/'/g, "''");
  return `'${json}'`;
}

async function main() {
  const client = new Client({ connectionString: STAGING_URL });
  await client.connect();

  const lines: string[] = [
    "-- Generated by scripts/build-migration-seed.ts",
    "-- Source: rds-staging (port 5500)",
    "",
  ];

  const users = await client.query<{
    id: string;
    email: string;
    role: string;
    name: string;
    third_party_id: string;
    created_at: Date;
    updated_at: Date;
    profile_id: number | null;
  }>(`
    SELECT id, email, role, name,
           "thirdPartyId" AS third_party_id,
           "createdAt"    AS created_at,
           "updatedAt"    AS updated_at,
           "profileId"    AS profile_id
      FROM "user"
     ORDER BY "createdAt"
  `);

  lines.push("-- auth.users");
  for (const u of users.rows) {
    const meta = {
      sub: u.third_party_id,
      name: u.name,
      email: u.email,
      email_verified: true,
    };
    // fixture/seed.sql과 동일한 35컬럼 세트.
    // Supabase Auth 쿼리가 빈 문자열을 기대하는 컬럼이 있어 NULL default로 두면 안 됨.
    lines.push(
      `INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at, email_change_token_new, email_change, email_change_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at, phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at, email_change_token_current, email_change_confirm_status, banned_until, reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at, is_anonymous) VALUES (${q(ANON_INSTANCE_ID)}, ${q(u.id)}, 'authenticated', 'authenticated', ${q(u.email)}, '', ${q(u.created_at)}, NULL, '', NULL, '', NULL, '', '', NULL, ${q(u.updated_at)}, '{"provider": "google", "providers": ["google"]}', ${jsonb(meta)}, NULL, ${q(u.created_at)}, ${q(u.updated_at)}, NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false);`,
    );
  }
  lines.push("");

  lines.push("-- auth.identities");
  for (const u of users.rows) {
    const identityData = {
      sub: u.third_party_id,
      name: u.name,
      email: u.email,
      provider_id: u.third_party_id,
      email_verified: true,
    };
    lines.push(
      `INSERT INTO auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at) VALUES (gen_random_uuid(), ${q(u.id)}, ${q(u.third_party_id)}, 'google', ${jsonb(identityData)}, ${q(u.updated_at)}, ${q(u.created_at)}, ${q(u.updated_at)});`,
    );
  }
  lines.push("");

  const authors = await client.query<{ id: number; name: string }>(
    `SELECT id, name FROM author ORDER BY id`,
  );
  lines.push("-- public.author");
  for (const a of authors.rows) {
    lines.push(`INSERT INTO public.author (id, name) VALUES (${a.id}, ${q(a.name)});`);
  }
  lines.push("");

  const books = await client.query(`
    SELECT "createdAt"    AS created_at,
           "updatedAt"    AS updated_at,
           version, isbn, title, contents, url, publisher,
           "thumbnailUrl" AS thumbnail_url,
           "publishedAt"  AS published_at,
           "authorId"     AS author_id
      FROM book
     ORDER BY isbn
  `);
  lines.push("-- public.book");
  for (const b of books.rows) {
    lines.push(
      `INSERT INTO public.book (created_at, updated_at, version, isbn, title, contents, url, publisher, thumbnail_url, published_at, author_id) VALUES (${q(b.created_at)}, ${q(b.updated_at)}, ${b.version}, ${q(b.isbn)}, ${q(b.title)}, ${q(b.contents)}, ${q(b.url)}, ${q(b.publisher)}, ${q(b.thumbnail_url)}, ${q(b.published_at)}, ${q(b.author_id)});`,
    );
  }
  lines.push("");

  const profiles = await client.query(`
    SELECT p."createdAt" AS created_at,
           p."updatedAt" AS updated_at,
           p.version, p.id, p.nickname,
           p."avatarUrl" AS avatar_url, p.bio,
           u.id   AS user_id,
           u.name AS name,
           u.role AS role
      FROM profile p
      JOIN "user" u ON u."profileId" = p.id
     ORDER BY p.id
  `);
  lines.push("-- public.profile (user merged in)");
  for (const p of profiles.rows) {
    lines.push(
      `INSERT INTO public.profile (created_at, updated_at, version, id, user_id, nickname, name, role, avatar_url, bio) VALUES (${q(p.created_at)}, ${q(p.updated_at)}, ${p.version}, ${p.id}, ${q(p.user_id)}, ${q(p.nickname)}, ${q(p.name)}, ${q(p.role)}, ${q(p.avatar_url)}, ${q(p.bio)});`,
    );
  }
  lines.push("");

  const posts = await client.query(`
    SELECT "createdAt" AS created_at,
           "updatedAt" AS updated_at,
           version, id, title, content, rating,
           "startDate" AS start_date,
           "isPrivate" AS is_private,
           "deletedAt" AS deleted_at,
           "userId"    AS user_id,
           "bookIsbn"  AS book_isbn
      FROM post
     ORDER BY id
  `);
  lines.push("-- public.post");
  for (const p of posts.rows) {
    lines.push(
      `INSERT INTO public.post (created_at, updated_at, version, id, title, content, rating, start_date, is_private, deleted_at, user_id, book_isbn) VALUES (${q(p.created_at)}, ${q(p.updated_at)}, ${p.version}, ${p.id}, ${q(p.title)}, ${q(p.content)}, ${p.rating}, ${q(p.start_date)}, ${p.is_private}, ${q(p.deleted_at)}, ${q(p.user_id)}, ${q(p.book_isbn)});`,
    );
  }
  lines.push("");

  const pmra = await client.query<{ profileId: number; authorId: number }>(
    `SELECT "profileId", "authorId" FROM profile_most_read_authors_author ORDER BY "profileId", "authorId"`,
  );
  lines.push("-- public.profile_most_read_author");
  for (const r of pmra.rows) {
    lines.push(
      `INSERT INTO public.profile_most_read_author (profile_id, author_id) VALUES (${r.profileId}, ${r.authorId});`,
    );
  }
  lines.push("");

  lines.push("-- Sequence resets");
  lines.push(
    `SELECT setval('public.author_id_seq', COALESCE((SELECT MAX(id) FROM public.author), 1));`,
  );
  lines.push(
    `SELECT setval('public.profile_id_seq', COALESCE((SELECT MAX(id) FROM public.profile), 1));`,
  );
  lines.push(
    `SELECT setval('public.post_id_seq', COALESCE((SELECT MAX(id) FROM public.post), 1));`,
  );

  await client.end();

  writeFileSync(OUTPUT_PATH, lines.join("\n") + "\n");

  console.log(`migration-seed.sql 생성 완료: ${OUTPUT_PATH}`);
  console.log(`  users:    ${users.rows.length}`);
  console.log(`  profiles: ${profiles.rows.length}`);
  console.log(`  books:    ${books.rows.length}`);
  console.log(`  authors:  ${authors.rows.length}`);
  console.log(`  posts:    ${posts.rows.length}`);
  console.log(`  pmra:     ${pmra.rows.length}`);
}

main().catch((err) => {
  console.error("실패:", err);
  process.exit(1);
});
